// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracaInzynierskaV1.Models;

namespace PracaInzynierskaV1.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20201118140235_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PracaInzynierskaV1.Models.DZguba", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("freward")
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("image")
                        .HasColumnType("image");

                    b.Property<string>("imageB")
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("location")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("DZguby");
                });
#pragma warning restore 612, 618
        }
    }
}
