// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracaInzynierskaV1.Models;

namespace PracaInzynierskaV1.Migrations
{
    [DbContext(typeof(MyDBContext))]
    partial class MyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PracaInzynierskaV1.Models.DUser", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("imageB")
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("surname")
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("id");

                    b.ToTable("DUser");
                });

            modelBuilder.Entity("PracaInzynierskaV1.Models.DZguba", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("freward")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("imageB")
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("location")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("user")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("user");

                    b.ToTable("DZguby");
                });

            modelBuilder.Entity("PracaInzynierskaV1.Models.DZguba_Elektronika", b =>
                {
                    b.HasBaseType("PracaInzynierskaV1.Models.DZguba");

                    b.Property<string>("Producent")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rodzaj")
                        .HasColumnType("nvarchar(50)");

                    b.ToTable("DZgubaElektronika");
                });

            modelBuilder.Entity("PracaInzynierskaV1.Models.DZguba_Ubranie", b =>
                {
                    b.HasBaseType("PracaInzynierskaV1.Models.DZguba");

                    b.Property<string>("Kolor")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Marka")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rodzaj")
                        .HasColumnType("nvarchar(50)");

                    b.ToTable("DZgubaUbranie");
                });

            modelBuilder.Entity("PracaInzynierskaV1.Models.DZguba_Zwierze", b =>
                {
                    b.HasBaseType("PracaInzynierskaV1.Models.DZguba");

                    b.Property<string>("gatunek")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("umaszczenie")
                        .HasColumnType("nvarchar(50)");

                    b.ToTable("DZgubaZwierze");
                });

            modelBuilder.Entity("PracaInzynierskaV1.Models.DZguba", b =>
                {
                    b.HasOne("PracaInzynierskaV1.Models.DUser", "DUser")
                        .WithMany("DZguba")
                        .HasForeignKey("user");

                    b.Navigation("DUser");
                });

            modelBuilder.Entity("PracaInzynierskaV1.Models.DZguba_Elektronika", b =>
                {
                    b.HasOne("PracaInzynierskaV1.Models.DZguba", null)
                        .WithOne()
                        .HasForeignKey("PracaInzynierskaV1.Models.DZguba_Elektronika", "id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PracaInzynierskaV1.Models.DZguba_Ubranie", b =>
                {
                    b.HasOne("PracaInzynierskaV1.Models.DZguba", null)
                        .WithOne()
                        .HasForeignKey("PracaInzynierskaV1.Models.DZguba_Ubranie", "id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PracaInzynierskaV1.Models.DZguba_Zwierze", b =>
                {
                    b.HasOne("PracaInzynierskaV1.Models.DZguba", null)
                        .WithOne()
                        .HasForeignKey("PracaInzynierskaV1.Models.DZguba_Zwierze", "id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PracaInzynierskaV1.Models.DUser", b =>
                {
                    b.Navigation("DZguba");
                });
#pragma warning restore 612, 618
        }
    }
}
